## Changelog
***

#### v2.1.1 : 7/29/2020

	* Fix up
		- the following error has been fixed up
			GUNA : ERROR ________________________________________________
			Traceback (most recent call last):
			  File "C:\Users\pouco\AppData\Roaming\Sublime Text 3\Packages\Guna\core\engine.py", line 705, in vSi_nURlYWk
			KeyError: 'dt'
